name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install dependencies
        run: flutter pub get
        working-directory: receipt_capture

      - name: Update CocoaPods
        run: pod repo update
        working-directory: receipt_capture/ios

      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign
        working-directory: receipt_capture

      - name: Prepare IPA payload
        run: |
          mkdir Payload
          mv Runner.app Payload/
          zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: receipt_capture/build/ios/iphoneos

      - name: Upload IPA to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: receipt_capture/build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first iOS release build (.ipa)"
